// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYCMBCnHAAE2mXPkSaVcR35QPdg75ML98',
    appId: '1:389879203145:web:79bd732052ce6f40d40698',
    messagingSenderId: '389879203145',
    projectId: 'quantum-654c6',
    authDomain: 'quantum-654c6.firebaseapp.com',
    storageBucket: 'quantum-654c6.appspot.com',
    measurementId: 'G-1CYJ42QBSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhsQq8pldi8oQVvpRXeADof5Y2p8hKDAI',
    appId: '1:389879203145:android:1d01cca12bd97ed0d40698',
    messagingSenderId: '389879203145',
    projectId: 'quantum-654c6',
    storageBucket: 'quantum-654c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBi3iWxysJ5llqzDkAQ18jE1_BsAG8UVU',
    appId: '1:389879203145:ios:02da546aaa51597bd40698',
    messagingSenderId: '389879203145',
    projectId: 'quantum-654c6',
    storageBucket: 'quantum-654c6.appspot.com',
    iosBundleId: 'com.example.quantumaware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBi3iWxysJ5llqzDkAQ18jE1_BsAG8UVU',
    appId: '1:389879203145:ios:02da546aaa51597bd40698',
    messagingSenderId: '389879203145',
    projectId: 'quantum-654c6',
    storageBucket: 'quantum-654c6.appspot.com',
    iosBundleId: 'com.example.quantumaware',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYCMBCnHAAE2mXPkSaVcR35QPdg75ML98',
    appId: '1:389879203145:web:73d171e2c0de34bed40698',
    messagingSenderId: '389879203145',
    projectId: 'quantum-654c6',
    authDomain: 'quantum-654c6.firebaseapp.com',
    storageBucket: 'quantum-654c6.appspot.com',
    measurementId: 'G-FD3T7K9H3R',
  );
}
